/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCard: typeof import('@nutui/nutui')['Card']
    NutConfigProvider: typeof import('@nutui/nutui')['ConfigProvider']
    NutGrid: typeof import('@nutui/nutui')['Grid']
    NutGridItem: typeof import('@nutui/nutui')['GridItem']
    NutImage: typeof import('@nutui/nutui')['Image']
    NutSearchbar: typeof import('@nutui/nutui')['Searchbar']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
